//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PrincipalType.
const (
	ApiKey      PrincipalType = "api_key"
	OauthClient PrincipalType = "oauth_client"
	System      PrincipalType = "system"
	User        PrincipalType = "user"
)

// Valid indicates whether the value is a known member of the PrincipalType enum.
func (e PrincipalType) Valid() bool {
	switch e {
	case ApiKey:
		return true
	case OauthClient:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// EventType defines model for EventType.
type EventType struct {
	Description string `json:"description"`

	// Name e.g. `call.missed`.
	Name string `json:"name"`
}

// EventTypeList defines model for EventTypeList.
type EventTypeList struct {
	Items []EventType `json:"items"`

	// NextCursor Pass as `?cursor=` to fetch the next page; absent on the last page.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// OpenApiDocument The full OpenAPI document served by this API. Free-form JSON.
type OpenApiDocument map[string]interface{}

// Principal The authenticated caller (docs/API.md §3).
type Principal struct {
	// Id The user, API key or OAuth client id.
	Id string `json:"id"`

	// Role Present for a signed-in person; absent for keys and clients.
	Role *string `json:"role,omitempty"`

	// Scopes e.g. `extensions:write`, `webhooks:write`.
	Scopes   []string            `json:"scopes"`
	TenantId *openapi_types.UUID `json:"tenant_id,omitempty"`
	Type     PrincipalType       `json:"type"`
}

// PrincipalType defines model for Principal.Type.
type PrincipalType string

// Problem RFC 9457 `application/problem+json` (docs/API.md §2).
type Problem struct {
	// Code Stable machine-readable error code, e.g. `scope_missing`.
	Code string `json:"code"`

	// Detail Plain-language explanation. Never a stack trace.
	Detail   string  `json:"detail"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`

	// Title Short, human-readable summary of the status code.
	Title string `json:"title"`

	// Type A URI identifying the problem type; `about:blank` when none is registered.
	Type string `json:"type"`
}

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// ListEventTypesParams defines parameters for ListEventTypes.
type ListEventTypesParams struct {
	// Limit Maximum items per page (docs/API.md §2).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque pagination cursor from a previous page's `next_cursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListEventTypes Webhook and admin-alert event types this server can emit
	// (GET /api/v1/event-types)
	ListEventTypes(w http.ResponseWriter, r *http.Request, params ListEventTypesParams)
	// GetMe Who am I, which scopes
	// (GET /api/v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// GetOpenapiSpec This API's own OpenAPI document
	// (GET /api/v1/openapi.json)
	GetOpenapiSpec(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListEventTypes operation middleware
func (siw *ServerInterfaceWrapper) ListEventTypes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventTypesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEventTypes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenapiSpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenapiSpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenapiSpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/openapi.json", wrapper.GetOpenapiSpec)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/me", wrapper.GetMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/v1/event-types", wrapper.ListEventTypes)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type ListEventTypesRequestObject struct {
	Params ListEventTypesParams
}

type ListEventTypesResponseObject interface {
	VisitListEventTypesResponse(w http.ResponseWriter) error
}

type ListEventTypes200JSONResponse EventTypeList

func (response ListEventTypes200JSONResponse) VisitListEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventTypesdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListEventTypesdefaultApplicationProblemPlusJSONResponse) VisitListEventTypesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Principal

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetMedefaultApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenapiSpecRequestObject struct {
}

type GetOpenapiSpecResponseObject interface {
	VisitGetOpenapiSpecResponse(w http.ResponseWriter) error
}

type GetOpenapiSpec200JSONResponse OpenApiDocument

func (response GetOpenapiSpec200JSONResponse) VisitGetOpenapiSpecResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListEventTypes Webhook and admin-alert event types this server can emit
	// (GET /api/v1/event-types)
	ListEventTypes(ctx context.Context, request ListEventTypesRequestObject) (ListEventTypesResponseObject, error)
	// GetMe Who am I, which scopes
	// (GET /api/v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// GetOpenapiSpec This API's own OpenAPI document
	// (GET /api/v1/openapi.json)
	GetOpenapiSpec(ctx context.Context, request GetOpenapiSpecRequestObject) (GetOpenapiSpecResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListEventTypes operation middleware
func (sh *strictHandler) ListEventTypes(w http.ResponseWriter, r *http.Request, params ListEventTypesParams) {
	var request ListEventTypesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEventTypes(ctx, request.(ListEventTypesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEventTypes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventTypesResponseObject); ok {
		if err := validResponse.VisitListEventTypesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenapiSpec operation middleware
func (sh *strictHandler) GetOpenapiSpec(w http.ResponseWriter, r *http.Request) {
	var request GetOpenapiSpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenapiSpec(ctx, request.(GetOpenapiSpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenapiSpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenapiSpecResponseObject); ok {
		if err := validResponse.VisitGetOpenapiSpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFb/bts2EH6VAzegGybbSdpimIthCLp18JA2RpNhfxRBdKbOFhuJZMlTEiMwsIfYO+w99ih7koGk/FtO",
	"NmD9T6JO9+P7Pt7dg5CmtkaTZi+GD8Kiw5qYXHx73ThvXHgqyEunLCujxVCcW/zUEFicKY3hDGS0hKkz",
	"NSBYR7fKND5Y0DMPuaZ7vk42eV9kQgUvnxpyc5EJjTWJoUifRSa8LKnGEJXnNnzx7JSeicUiE2eqVryf",
	"0Fu8V3VTg2KqPVhyMTJ8VRjpB6fjUb8u4K8/T74+FLuKbjdDFzTFpmIxfHmUiTq5F8OTo/CmdHo7zpYZ",
	"Ks00IycWIUdH3hrtKUI4dmZSUR0epdFMOmaP1lZKRugGNll889GHUh42cvjS0VQMxReDNUeD9NUPln5j",
	"xG0wTjWQc8Z1lR+sWxchwk+3pPky1vAgrDOWHKuU+JbPPSqWyO3YCerP+pBLrKp+rbynItK9z6OjT41y",
	"VIjhh+Rpu4ir1T9m8pEkh4CrXM+U5/18I/VbD4/Bty58sQqFzuE8lrZW636FY/Qe0EP+Q7L4Pgc2MCWW",
	"JXBJEH6O6nsFOPGkGYyOHyr06cPTiKQSukA4t6RPrfrRyKZeaqkoVMgNq/EGIOwa2hXGZUkwbaoKopfx",
	"CIrWDXhyt1TAZA5cKg9BMvDGEfWmxtXwy8X5u77oyGbslJbKYrUPU4iFDZekOQidCgiioD1RPo93cofK",
	"ottf48llITm4oTkYB+enDZcgKxVqUEUHsJlwpurQ6dhR5GZqHCB4NdNU9JQOrcMbvaIufL6huQfURRvH",
	"d0bx0ljyh+4D3TNpr4z2wzunmPIM8jualMbcLE+C15Vy99zvKpRJo+brBFTgCFkMRdOoQmSH/n4QpEPX",
	"+iACjiITaNX1DYUuaAJT16k+kQk/90y1uNpztSvTVbQVAFedKlm1wG1w3r95Dd+9ePkt5If6Yd7dwrfl",
	"Ik3RwfAF46QiqFGWSlPPERbxILXG8E8GiZ2Y+nVoV0rP8k56C2JUHSofV6h0r0I9a8K8oXtbYZqIfXhH",
	"txTFxShvgB1K6vSttGfUkjqJ94zcbGpiNWkywYq7pH1RGscZlE2Nel22b+oa3RzMNDaj5DfC0H9MMjuT",
	"BX59PwJVhEs9nSs9i75awiD88wpynJiGh5MK9U0OdyVp0EYTKA+OZsozOSqeboGtrFKNKxyyRPaKkH25",
	"LSKiU9PdQULvaPyy0xFgUYdLbxxjlcWTO5q0Fz2955XS9zm8PhvFHhA4nUMkwaXNZ1OgUZyVkqQ9pUYW",
	"kVLkAngWZUm9k/7Reu/YOFsTKs6Uvg+pikzckvMp/eNgYSxptEoMxfP+cXRkkcuojwFaNbg9HlCYbL2A",
	"SjyeEXdDEe1AImNlZtB2IyBdWKM0e/DNJPwyoTDedm7hi1houIMRg1ERk/a8mqpeZFur5Ifuabw2GaTF",
	"bpE9adjupIurnUXr5OjokSXrvy1X26tG14qV9kszbWGMcPdTp2j3xu4Iq5Q3FrhMtJdTDMVvLQ9Ba1Gc",
	"PazI8WaYNKLjxHYgUQOl3ZVxFpAWNTGKq+B2KYmaDiphtFSoj2pvZ/Tfv//RMRUPj95or4voIg0CUAyl",
	"qQq/L5Sfid+S+IzsrbeSDuYu2ypD87JLw/+FudIA1jDK4K5UsmxxeJSX9jb3l+V1MjRuJpWSryBAg0p7",
	"0AY8SUfsu4fjHtrnKcyFJfk5Yd9dTQ+A/292zx1oL9vzZx7Mnd7z0IHxYvHPAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
