package installer

import (
	"context"
	"os"
	"path/filepath"
)

// Host files linx-backup-agent's install writes (docs/BACKUP.md §8 step 3).
const (
	BackupAgentPath      = "/usr/local/bin/linx-backup-agent"
	BackupAgentService   = "linx-backup-agent.service"
	BackupAgentTimer     = "linx-backup-agent.timer"
	backupAgentUnitPath  = "/etc/systemd/system/" + BackupAgentService
	backupAgentTimerPath = "/etc/systemd/system/" + BackupAgentTimer
)

// ResticPlan installs restic (BSD-2-Clause), which linx backup and linx
// restore run for all encryption and storage (ADR-055), from Ubuntu's own
// signed package archive — the same trust as nftables — unless it's
// already there.
func ResticPlan(ctx context.Context, r Runner) Plan {
	if _, err := r.Run(ctx, nil, "restic", "version"); err == nil {
		return nil
	}
	return Plan{
		aptStep("Refresh the package list", "update"),
		aptStep("Install the backup tool (restic)", "install", "-y", "restic"),
	}
}

// BackupAgentPlan installs linx-backup-agent, built alongside linx in the
// same directory (make build's bin/), and a systemd timer that runs it
// every minute: it's what checks whether a backup is due (the admin's
// schedule, or a "back up now" from the browser) or a restore is waiting
// (the setup wizard's) and, if so, runs and reports it (docs/BACKUP.md §4,
// §8 step 3). No plan (nothing to install) if
// linx-backup-agent isn't next to the running linx binary — a dev build of
// one binary only, say — the same rule FirewallSyncPlan follows.
func BackupAgentPlan(linxPath string, resolve func(string) (string, error), stat func(string) (os.FileInfo, error)) Plan {
	if linxPath == "" {
		return nil
	}
	src := filepath.Join(filepath.Dir(linxPath), "linx-backup-agent")
	if _, err := stat(src); err != nil {
		return nil
	}
	var p Plan
	a, errA := resolve(src)
	b, errB := resolve(BackupAgentPath)
	if errA != nil || errB != nil || filepath.Clean(a) != filepath.Clean(b) {
		p = append(p, Step{
			Title: "Install linx-backup-agent as " + BackupAgentPath,
			Cmd:   &Cmd{Name: "install", Args: []string{"-m", "0755", "-o", "root", "-g", "root", src, BackupAgentPath}},
		})
	}
	return append(p,
		fileStep("Write the backup agent service", backupAgentUnitPath, []byte(backupAgentServiceUnit), 0o644, 0o755),
		fileStep("Run it every minute", backupAgentTimerPath, []byte(backupAgentTimerUnit), 0o644, 0o755),
		cmdStep("Tell the system about the timer", "systemctl", "daemon-reload"),
		cmdStep("Turn the timer on", "systemctl", "enable", BackupAgentTimer),
		cmdStep("Start it now", "systemctl", "restart", BackupAgentTimer),
	)
}

const backupAgentServiceUnit = `# Generated by linx setup. Changes are overwritten when setup runs again.
[Unit]
Description=Run a due Linx backup and report its outcome
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=` + BackupAgentPath + `
`

const backupAgentTimerUnit = `# Generated by linx setup. Changes are overwritten when setup runs again.
[Unit]
Description=Check every minute whether a Linx backup is due or a restore is waiting

[Timer]
OnBootSec=1min
OnUnitActiveSec=1min
Unit=` + BackupAgentService + `

[Install]
WantedBy=timers.target
`
