package installer

import (
	"os"
	"path/filepath"
)

// Host files linx-firewall-sync's install writes (docs/TRUNKS.md §12/§13
// step 6).
const (
	FirewallSyncPath      = "/usr/local/bin/linx-firewall-sync"
	FirewallSyncService   = "linx-firewall-sync.service"
	FirewallSyncTimer     = "linx-firewall-sync.timer"
	firewallSyncUnitPath  = "/etc/systemd/system/" + FirewallSyncService
	firewallSyncTimerPath = "/etc/systemd/system/" + FirewallSyncTimer
)

// FirewallSyncPlan installs linx-firewall-sync, built alongside linx in the
// same directory (make build's bin/), and a systemd timer that runs it
// once a minute: it's what keeps TrunkAddressSet and TrunkPlainAddressSet
// matching the trunks in the database (internal/nftset, ADR-047), so a
// provider's address is admitted only for as long as a trunk still uses
// it. No plan (nothing to install) if linx-firewall-sync isn't next to the
// running linx binary — a dev build of one binary only, say.
func FirewallSyncPlan(linxPath string, resolve func(string) (string, error), stat func(string) (os.FileInfo, error)) Plan {
	if linxPath == "" {
		return nil
	}
	src := filepath.Join(filepath.Dir(linxPath), "linx-firewall-sync")
	if _, err := stat(src); err != nil {
		return nil
	}
	var p Plan
	a, errA := resolve(src)
	b, errB := resolve(FirewallSyncPath)
	if errA != nil || errB != nil || filepath.Clean(a) != filepath.Clean(b) {
		p = append(p, Step{
			Title: "Install linx-firewall-sync as " + FirewallSyncPath,
			Cmd:   &Cmd{Name: "install", Args: []string{"-m", "0755", "-o", "root", "-g", "root", src, FirewallSyncPath}},
		})
	}
	return append(p,
		fileStep("Write the phone-line firewall sync service", firewallSyncUnitPath, []byte(firewallSyncServiceUnit), 0o644, 0o755),
		fileStep("Run it every minute", firewallSyncTimerPath, []byte(firewallSyncTimerUnit), 0o644, 0o755),
		cmdStep("Tell the system about the timer", "systemctl", "daemon-reload"),
		cmdStep("Turn the timer on", "systemctl", "enable", FirewallSyncTimer),
		cmdStep("Start it now", "systemctl", "restart", FirewallSyncTimer),
	)
}

const firewallSyncServiceUnit = `# Generated by linx setup. Changes are overwritten when setup runs again.
[Unit]
Description=Keep Linx's firewall matching its phone-line providers
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=` + FirewallSyncPath + `
`

const firewallSyncTimerUnit = `# Generated by linx setup. Changes are overwritten when setup runs again.
[Unit]
Description=Run linx-firewall-sync every minute

[Timer]
OnBootSec=30s
OnUnitActiveSec=1min
Unit=` + FirewallSyncService + `

[Install]
WantedBy=timers.target
`
