package installer

import (
	"os"
	"path/filepath"
)

// Host files linx-ops-agent's install writes (docs/ADMIN.md §9, ADR-056).
const (
	OpsAgentPath     = "/usr/local/bin/linx-ops-agent"
	OpsAgentService  = "linx-ops-agent.service"
	opsAgentUnitPath = "/etc/systemd/system/" + OpsAgentService
)

// OpsAgentPlan installs linx-ops-agent, built alongside linx in the same
// directory (make build's bin/), as a systemd service that's always
// running: it keeps the link System → Status uses to show each service's
// state and log and to restart one (internal/ops). Unlike the backup
// agent it isn't a timer: a log or a restart shouldn't wait a minute. No
// plan if linx-ops-agent isn't next to the running linx binary, the same
// rule BackupAgentPlan follows.
func OpsAgentPlan(linxPath string, resolve func(string) (string, error), stat func(string) (os.FileInfo, error)) Plan {
	if linxPath == "" {
		return nil
	}
	src := filepath.Join(filepath.Dir(linxPath), "linx-ops-agent")
	if _, err := stat(src); err != nil {
		return nil
	}
	var p Plan
	a, errA := resolve(src)
	b, errB := resolve(OpsAgentPath)
	if errA != nil || errB != nil || filepath.Clean(a) != filepath.Clean(b) {
		p = append(p, Step{
			Title: "Install linx-ops-agent as " + OpsAgentPath,
			Cmd:   &Cmd{Name: "install", Args: []string{"-m", "0755", "-o", "root", "-g", "root", src, OpsAgentPath}},
		})
	}
	return append(p,
		fileStep("Write the server helper service", opsAgentUnitPath, []byte(opsAgentServiceUnit), 0o644, 0o755),
		cmdStep("Tell the system about it", "systemctl", "daemon-reload"),
		cmdStep("Start it at boot", "systemctl", "enable", OpsAgentService),
		cmdStep("Start it now", "systemctl", "restart", OpsAgentService),
	)
}

const opsAgentServiceUnit = `# Generated by linx setup. Changes are overwritten when setup runs again.
[Unit]
Description=Linx server helper: service health, logs and restart for System → Status
After=docker.service
Requires=docker.service

[Service]
ExecStart=` + OpsAgentPath + `
Restart=always
RestartSec=5
NoNewPrivileges=yes

[Install]
WantedBy=multi-user.target
`
