package installer

import (
	"crypto/rand"
	"fmt"
	"net"
	"net/netip"
	"os"
)

// Container management UIs offered by setup (ADR-019).
const (
	ContainerUINone      = "none"
	ContainerUIPortainer = "portainer"
)

// ContainerUIs lists the valid choices, default first.
var ContainerUIs = []string{ContainerUINone, ContainerUIPortainer}

// portainerImage is Portainer CE LTS, pinned by digest (multi-arch index).
const portainerImage = "portainer/portainer-ce:2.45.1@sha256:4d616db18cfeb5dd41a69c0958bc825c84483ea9cde1106eb82a5d26f3bd8b0e"

const (
	portainerDir          = "/etc/linx/portainer"
	portainerPasswordFile = SecretsDir + "/portainer_admin_password"
	portainerPort         = 9443
)

// PortainerSetup is the result of planning a Portainer install.
type PortainerSetup struct {
	Plan     Plan
	URL      string
	Password string
	// LocalOnly is true when the server has no private LAN address, so
	// Portainer listens only on 127.0.0.1 and is reached through an SSH tunnel.
	LocalOnly bool
}

// PortainerPlan writes a Compose file for Portainer CE bound to bindIP only,
// with a generated admin password kept as a root-only file mounted as a Compose
// secret. An existing password is reused so re-running setup doesn't lock the
// owner out.
func PortainerPlan(bindIP netip.Addr) PortainerSetup {
	pw := existingOrNewPassword(portainerPasswordFile)
	s := PortainerSetup{
		Password:  pw,
		LocalOnly: bindIP.IsLoopback(),
		URL:       fmt.Sprintf("https://%s", net.JoinHostPort(bindIP.String(), fmt.Sprint(portainerPort))),
	}
	s.Plan = Plan{
		fileStep("Save the Portainer admin password (readable by root only)", portainerPasswordFile, []byte(pw), 0o600, 0o700),
		fileStep("Write the Portainer configuration", portainerDir+"/compose.yaml", portainerCompose(bindIP), 0o644, 0o755),
		cmdStep("Start Portainer", "docker", "compose", "--file", portainerDir+"/compose.yaml", "up", "--detach", "--wait"),
	}
	return s
}

func portainerCompose(bindIP netip.Addr) []byte {
	return fmt.Appendf(nil, `# Generated by linx setup. Changes are overwritten when setup runs again.
# Portainer can control every container on this server (root-equivalent).
# It listens on the local network only; never forward this port on your router.
name: linx-portainer
services:
  portainer:
    image: %s
    container_name: linx-portainer
    restart: unless-stopped
    command: ["--admin-password-file", "/run/secrets/portainer_admin_password"]
    ports:
      - "%s:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    secrets:
      - portainer_admin_password
    security_opt:
      - no-new-privileges:true
volumes:
  data:
    name: linx-portainer-data
secrets:
  portainer_admin_password:
    file: %s
`, portainerImage, net.JoinHostPort(bindIP.String(), fmt.Sprint(portainerPort)), portainerPasswordFile)
}

func existingOrNewPassword(path string) string {
	if b, err := os.ReadFile(path); err == nil && len(b) > 0 {
		return string(b)
	}
	return rand.Text() // 26 characters, 130 bits
}

// LANAddress returns the address other devices on the local network use to
// reach this server: the source address of the default route. If that address
// isn't private (e.g. a cloud server with a public IP), it returns 127.0.0.1 so
// management UIs never face the internet.
func LANAddress() netip.Addr {
	loopback := netip.AddrFrom4([4]byte{127, 0, 0, 1})
	// UDP "dial" sends no packets; it only asks the kernel which source
	// address it would use.
	c, err := net.Dial("udp4", "192.0.2.1:9") // TEST-NET-1, never routed
	if err != nil {
		return loopback
	}
	defer c.Close()
	ap, err := netip.ParseAddrPort(c.LocalAddr().String())
	if err != nil {
		return loopback
	}
	return lanOrLoopback(ap.Addr())
}

func lanOrLoopback(a netip.Addr) netip.Addr {
	a = a.Unmap()
	if a.IsPrivate() {
		return a
	}
	return netip.AddrFrom4([4]byte{127, 0, 0, 1})
}
