package installer

import (
	"fmt"
	"regexp"
	"strings"

	"linxpbx.com/linx/deploy/compose"
)

const (
	// StackDir holds the Linx Compose stack. compose.yaml refers to secrets as
	// ./secrets/..., which is SecretsDir.
	StackDir  = "/etc/linx"
	stackFile = StackDir + "/compose.yaml"
	stackEnv  = StackDir + "/.env"
	// DNSTokenPath is the DNS provider API token (Docker secret linx_dns_token).
	DNSTokenPath = SecretsDir + "/linx_dns_token"
	// nonrootGID is the distroless "nonroot" group that Linx service images
	// run as. The DNS token is root-owned and readable by this group only.
	nonrootGID = 65532
)

// StackSetup is the result of planning the Linx stack.
type StackSetup struct {
	Plan Plan
	// Names describes the certificate's DNS names, for the summary.
	Names string
}

// ImageTag returns the Linx image tag CI publishes for this build
// ("sha-<full commit>"), or an error if the binary wasn't built from a known
// commit.
func ImageTag(commit string) (string, error) {
	if !commitRE.MatchString(commit) {
		return "", fmt.Errorf("this linx build doesn't say which version it is (commit %q), so setup can't pick matching service images; build it with make build from a checkout of master", commit)
	}
	return "sha-" + commit, nil
}

var commitRE = regexp.MustCompile(`^[0-9a-f]{40}$`)

// StackPlan saves the DNS token, installs compose.yaml and its .env, gets the
// first public certificate and starts the stack. It must run after PKIPlan,
// because step-ca's volume and password must exist before "up".
func StackPlan(c Config, dnsToken, imageTag string) StackSetup {
	dc := []string{"compose", "--file", stackFile}
	tokenStep := fileStep("Save the DNS token (readable by root and the certificate service only)",
		DNSTokenPath, []byte(strings.TrimSpace(dnsToken)), 0o440, 0o700)
	tokenStep.File.Gid = nonrootGID
	kind := "trusted certificate"
	if c.Certificates.Staging {
		kind = "test certificate"
	}
	return StackSetup{
		Names: certNames(c),
		Plan: Plan{
			tokenStep,
			fileStep("Write the Linx services configuration", stackFile, compose.File, 0o644, 0o755),
			fileStep("Write the Linx settings for "+c.Domain.Name, stackEnv, stackDotEnv(c, imageTag), 0o644, 0o755),
			cmdStep("Download the Linx service images", "docker", append(dc, "pull", "--quiet")...),
			cmdStep("Get a "+kind+" for "+certNames(c)+" (can take a few minutes)",
				"docker", append(dc, "run", "--rm", "certd", "-once")...),
			cmdStep("Start the Linx services", "docker", append(dc, "up", "--detach", "--wait")...),
		},
	}
}

// stackDotEnv renders the non-secret settings compose.yaml reads. Every value
// is validated before it gets here (Config.Validate, ImageTag), so none needs
// quoting.
func stackDotEnv(c Config, imageTag string) []byte {
	return fmt.Appendf(nil, `# Generated by linx setup from %s. Changes are overwritten when setup runs again.
LINX_VERSION=%s
LINX_DOMAIN=%s
LINX_DNS_PROVIDER=%s
LINX_ACME_EMAIL=%s
LINX_ACME_STAGING=%t
LINX_CERT_WILDCARD=%t
`, ConfigPath, imageTag, c.Domain.Name, c.Domain.DNSProvider, c.Certificates.Email, c.Certificates.Staging, c.Certificates.Wildcard)
}

// certNames describes internal/certs.Config.Names for the plan and summary.
func certNames(c Config) string {
	if c.Certificates.Wildcard {
		return "*." + c.Domain.Name
	}
	return "admin., api., meet., provision., sip. and turn." + c.Domain.Name
}

// ValidateDNSToken does a basic sanity check; the provider checks the rest
// when the first certificate is requested.
func ValidateDNSToken(t string) error {
	t = strings.TrimSpace(t)
	switch {
	case t == "":
		return fmt.Errorf("the token is empty")
	case strings.ContainsAny(t, " \t\r\n"):
		return fmt.Errorf("the token can't contain spaces; copy just the token")
	case len(t) < 20 || len(t) > 200:
		return fmt.Errorf("that doesn't look like a DNS provider token (%d characters)", len(t))
	}
	return nil
}
