package installer

import (
	"fmt"
	"net/netip"
	"strings"

	"linxpbx.com/linx/internal/certs"
	"linxpbx.com/linx/internal/dnsname"
	"linxpbx.com/linx/internal/install"
)

// The web install's certificate page (docs/INSTALL.md §4): what the host
// shows and runs once the plain page's answers are saved.

// CertMode is how the first certificate is got for a front door: through
// port 443 without a token, unless the front door can't pass Let's
// Encrypt's check through to Linx (an HTTP-only proxy decrypts it; home
// only isn't reachable at all), where the DNS token is asked instead.
func CertMode(kind string) string {
	if kind == FrontDoorHTTPProxy || kind == FrontDoorHomeOnly {
		return install.CertToken
	}
	return install.CertPort443
}

// CertView is the certificate page for the saved answers: its mode, the
// record to add and the front door's own steps.
func CertView(c Config, lan LAN, facts install.Facts) install.CertView {
	v := install.CertView{Mode: CertMode(c.FrontDoor.Kind), Domain: c.Domain.Name, FrontDoor: c.FrontDoor.Kind, Setup: DoorSetup(c, lan)}
	if v.Mode == install.CertPort443 {
		for _, h := range certs.BootstrapHosts {
			v.AddRecords = append(v.AddRecords, install.Record{Type: "A", Name: dnsname.Host(h, c.Domain.Name), Value: facts.PublicAddress})
		}
	}
	return v
}

// DoorSetup is what to do on the front door before Let's Encrypt (or a
// browser) can get through it, as the certificate page shows it; nil when
// there's nothing (a rented server where Linx takes 443, or home only).
func DoorSetup(c Config, lan LAN) *install.DoorSetup {
	d, linx, udp := c.Domain.Name, lan.BindAddress(), c.FrontDoor.UDPPort()
	switch c.FrontDoor.Kind {
	case FrontDoorPangolin:
		p := c.FrontDoor.ProxyAddress
		return &install.DoorSetup{
			Files: []install.SetupFile{{Title: "the block for Pangolin", Path: "config/traefik/dynamic_config.yml", Text: string(PangolinTraefik(d, linx))}},
			Steps: []string{
				"On the Pangolin machine (" + p + "), add the block below to the end of config/traefik/dynamic_config.yml. If that file already has a line that is exactly “tcp:”, don't add a second one: put the routers and services under the existing one. Traefik picks it up by itself.",
				fmt.Sprintf("On your router, keep TCP port 443 going to Pangolin (%s), and send UDP port %d to this server (%s).", p, udp, linx),
			},
		}
	case FrontDoorNginx:
		return &install.DoorSetup{
			Files: []install.SetupFile{
				{Title: "the block for nginx", Path: "nginx.conf, at the top level (next to http { }, not inside it)", Text: string(NginxStream(d, linx))},
				{Title: "the block for HAProxy", Path: "your frontend on port 443", Text: string(HAProxySnippet(d, linx))},
			},
			Steps: []string{
				"Add one of the blocks below to the program that uses port 443 (" + c.FrontDoor.ProxyAddress + "), then reload it. With nginx, your own websites move from port 443 to " + nginxSitesHop + ": see " + NginxStepsFile + " on this server.",
				fmt.Sprintf("On your router, keep TCP port 443 going to that machine, and send UDP port %d to this server (%s).", udp, linx),
			},
		}
	case FrontDoorHTTPProxy:
		return &install.DoorSetup{
			Files: []install.SetupFile{{Title: "the block for Caddy", Path: "your Caddyfile", Text: string(CaddyConfig(d, linx))}},
			Steps: []string{
				"Add the block below to your Caddyfile and reload Caddy. With Nginx Proxy Manager, follow " + HTTPProxyStepsFile + " on this server instead.",
				fmt.Sprintf("On your router, keep TCP port 443 going to your proxy (%s), and send TCP port %d and UDP port %d to this server (%s).", c.FrontDoor.ProxyAddress, TURNTLSPort, udp, linx),
			},
		}
	case FrontDoorLinx443:
		if lan.OK() {
			return &install.DoorSetup{Steps: []string{fmt.Sprintf("On your router, send TCP and UDP port 443 to this server (%s).", lan.Address)}}
		}
	}
	return nil
}

// installEnvCert is the certificate page's part of install.env.
func installEnvCert(c Config, lan LAN) string {
	fd := FrontDoorFor(c, lan)
	// certd's own profile stays off: "up" never starts it, and "run"
	// starts a service it names whatever its profile.
	return fmt.Sprintf(`# The certificate page (docs/INSTALL.md §4): the front door is %s.
LINX_DOMAIN=%s
LINX_ACME_EMAIL=%s
LINX_DNS_PROVIDER=%s
LINX_TRUSTED_PROXIES=%s
LINX_PROXY_PROTOCOL=%t
LINX_WEB_ADDRESS=%s
LINX_SNI_ADDRESS=%s
COMPOSE_PROFILES=%s
`, c.FrontDoor.Kind, c.Domain.Name, c.Certificates.Email, c.Domain.DNSProvider, fd.TrustedProxies, fd.ProxyProtocol,
		fd.WebAddress, fd.SNIAddress, fd.ComposeProfiles)
}

// InstallCertEnv is install.env for the certificate page.
func InstallCertEnv(c Config, lan LAN, imageTag string, address netip.Addr) []byte {
	return []byte(installEnv(imageTag, address) + installEnvCert(c, lan))
}

func installEnv(imageTag string, address netip.Addr) string {
	return fmt.Sprintf("# Generated by linx setup for the web install's first page (docs/INSTALL.md).\n"+
		"LINX_VERSION=%s\nLINX_INSTALL_ADDRESS=%s\n", imageTag, address)
}

// InstallCertPlan writes the front door's files and starts the install's
// stack again with its settings: the control plane's HTTPS port where the
// front door reaches it, and Linx's own port 443 router when Linx takes
// 443 or is home only.
func InstallCertPlan(c Config, lan LAN, imageTag string, address netip.Addr) Plan {
	files, _ := FrontDoorPlan(c, lan)
	dc := installCompose()
	return append(files,
		fileStep("Write the installer's settings", installStackEnv, InstallCertEnv(c, lan, imageTag, address), 0o644, 0o755),
		cmdStep("Start Linx's web port", "docker", append(dc, "up", "--detach", "--wait", "--remove-orphans")...),
	)
}

// CertdRun is the docker arguments that run certd from the install's
// stack with args; token mounts the DNS token for that run only.
func CertdRun(token bool, args ...string) []string {
	a := append(installCompose(), "run", "--rm", "--no-TTY")
	if token {
		a = append(a, "--volume", DNSTokenPath+":/run/secrets/linx_dns_token:ro")
	}
	return append(append(a, "certd"), args...)
}

// RecordsArgs is certd -records for the certificate page's token mode: the
// public names at this network's public address, or home only's at the
// home address.
func RecordsArgs(c Config, lan LAN) []string {
	args := []string{"-records", strings.Join(PublicHosts, ",")}
	if a := FrontDoorFor(c, lan).DNSAddress; a != "" {
		args = append(args, "-address", a)
	}
	return args
}

// SaveDNSTokenPlan saves the DNS token as linx_dns_token, readable by root
// and the certificate service only (as StackPlan does).
func SaveDNSTokenPlan(token string) Plan {
	s := fileStep("Save the DNS token (readable by root and the certificate service only)",
		DNSTokenPath, []byte(strings.TrimSpace(token)), 0o440, 0o700)
	s.File.Gid = nonrootGID
	return Plan{s}
}
