-- Tenant and audit log (ADR-026; docs/API.md §3, §6).
-- IDs are UUIDv7, generated by the application, never by the database.

CREATE TABLE tenant (
    id         uuid PRIMARY KEY,
    name       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Every write, key use for writes, replay and failed auth (docs/API.md §2).
CREATE TABLE audit_log (
    id        uuid PRIMARY KEY,
    at        timestamptz NOT NULL DEFAULT now(),
    tenant_id uuid REFERENCES tenant (id),
    -- "user:<id>", "api_key:<id>", "oauth_client:<id>" or "system".
    actor     text NOT NULL,
    ip        inet,
    action    text NOT NULL,
    target    text,
    result    text NOT NULL,
    detail    jsonb
);

CREATE INDEX audit_log_tenant_at_idx ON audit_log (tenant_id, at DESC);
