-- Call history (ADR-070, docs/PHASE1F.md §9, Phase 1F step 15).
--
-- Asterisk's call-record module (cdr_adaptive_odbc) adds one row here for
-- every pair of channels in a call: the caller and each phone or line it
-- rang, or the caller alone when Linx itself answered (a message, the
-- echo test, voicemail). linkedid ties every row of one call together.
-- The linx_asterisk role may only add rows: it can't read, change or
-- delete them, so a phone system taken over can't rewrite history. The
-- rows are written even while the control plane is away; the control
-- plane turns them into one line per call (call_record) and removes them
-- with the call when it's older than the setting below.
--
-- Times are UTC without a zone (cdr.conf's usegmtime): what Asterisk
-- sends has no zone, and the database's own zone must not change it.
CREATE TABLE asterisk.cdr (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started     timestamp NOT NULL,
    answered    timestamp,
    ended       timestamp NOT NULL,
    clid        text NOT NULL DEFAULT '',
    src         text NOT NULL DEFAULT '',
    dst         text NOT NULL DEFAULT '',
    dcontext    text NOT NULL DEFAULT '',
    channel     text NOT NULL DEFAULT '',
    dstchannel  text NOT NULL DEFAULT '',
    lastapp     text NOT NULL DEFAULT '',
    lastdata    text NOT NULL DEFAULT '',
    duration    integer NOT NULL DEFAULT 0,
    billsec     integer NOT NULL DEFAULT 0,
    disposition text NOT NULL DEFAULT '',
    uniqueid    text NOT NULL DEFAULT '',
    linkedid    text NOT NULL DEFAULT '',
    sequence    integer NOT NULL DEFAULT 0,
    -- Set by the dialplan (internal/asteriskconf): what a phone dialled,
    -- the phone number a call from a line was for, and the place each
    -- ringing step was.
    linx_dialled text NOT NULL DEFAULT '',
    linx_did    text NOT NULL DEFAULT '',
    linx_step   text NOT NULL DEFAULT ''
);
CREATE INDEX cdr_linkedid_idx ON asterisk.cdr (linkedid);
GRANT INSERT ON asterisk.cdr TO linx_asterisk;

-- One line per call, made by the control plane from the rows above
-- (internal/callhistory). Names and numbers are kept as they were at the
-- time, so a call still reads right after a person or a line is renamed
-- or removed. steps is the call's way through Linx, for the detail
-- ("Rang Sales: Sara, Omar · nobody answered in 25 s").
CREATE TABLE call_record (
    id                     uuid PRIMARY KEY,
    tenant_id              uuid NOT NULL REFERENCES tenant (id),
    linkedid               text NOT NULL UNIQUE,
    direction              text NOT NULL CHECK (direction IN ('internal', 'inbound', 'outbound')),
    started_at             timestamptz NOT NULL,
    answered_at            timestamptz,
    ended_at               timestamptz NOT NULL,
    talk_seconds           integer NOT NULL DEFAULT 0 CHECK (talk_seconds >= 0),
    result                 text NOT NULL CHECK (result IN ('answered', 'missed', 'voicemail', 'not_available',
                               'not_in_use', 'closed', 'not_permitted', 'no_lines', 'limit_reached', 'echo_test', 'busy', 'failed')),
    -- Someone rang and nobody answered (also with result voicemail).
    rang_unanswered        boolean NOT NULL DEFAULT false,
    from_number            text NOT NULL DEFAULT '' CHECK (length(from_number) <= 40),
    from_name              text NOT NULL DEFAULT '' CHECK (length(from_name) <= 100),
    from_extension_id      uuid REFERENCES extension (id) ON DELETE SET NULL,
    to_number              text NOT NULL DEFAULT '' CHECK (length(to_number) <= 40),
    to_name                text NOT NULL DEFAULT '' CHECK (length(to_name) <= 100),
    to_extension_id        uuid REFERENCES extension (id) ON DELETE SET NULL,
    trunk_id               uuid REFERENCES trunk (id) ON DELETE SET NULL,
    trunk_name             text NOT NULL DEFAULT '' CHECK (length(trunk_name) <= 100),
    ring_group_id          uuid REFERENCES ring_group (id) ON DELETE SET NULL,
    ring_group_name        text NOT NULL DEFAULT '' CHECK (length(ring_group_name) <= 100),
    answered_by_extension_id uuid REFERENCES extension (id) ON DELETE SET NULL,
    answered_by_name       text NOT NULL DEFAULT '' CHECK (length(answered_by_name) <= 100),
    -- The channel that recorded a voicemail (voicemail_message.source),
    -- looked up when shown: a message deleted since simply isn't there.
    voicemail_source       text NOT NULL DEFAULT '',
    voicemail_box_name     text NOT NULL DEFAULT '' CHECK (length(voicemail_box_name) <= 100),
    steps                  jsonb NOT NULL DEFAULT '[]',
    updated_at             timestamptz NOT NULL
);
CREATE INDEX call_record_tenant_idx ON call_record (tenant_id, started_at DESC, id DESC);
CREATE INDEX call_record_ended_idx ON call_record (ended_at);

-- Who a call was theirs: the calling person, everyone it rang, who
-- answered. missed: rang them and nobody answered it.
CREATE TABLE call_record_party (
    call_id      uuid NOT NULL REFERENCES call_record (id) ON DELETE CASCADE,
    extension_id uuid NOT NULL REFERENCES extension (id) ON DELETE CASCADE,
    started_at   timestamptz NOT NULL,
    missed       boolean NOT NULL,
    PRIMARY KEY (call_id, extension_id)
);
CREATE INDEX call_record_party_idx ON call_record_party (extension_id, started_at DESC);

-- How long calls are kept (System → Settings, 1 year by default) and how
-- far the control plane has read asterisk.cdr.
ALTER TABLE pbx_setting ADD COLUMN call_history_keep_days smallint NOT NULL DEFAULT 365
    CHECK (call_history_keep_days BETWEEN 30 AND 730);
ALTER TABLE pbx_setting ADD COLUMN call_history_read_id bigint NOT NULL DEFAULT 0;

-- The Call history badge: missed calls since the person last opened it.
ALTER TABLE app_user ADD COLUMN calls_seen_at timestamptz;
